//package exception_demo;
//
//public class HandleException {
//    public static void main(String[] args) {
//        try{
//            int number = 9;
//            int zero = 0;
//            int result = number/zero;
//        } catch () ArithmeticException e
//    }
//}
